### PR TITLE
Consider scala patch version for scalac-scoverage-plugin

### LINKED ISSUE #94: Consider using Scala's patch version to determine the artifactId of the scalac-scoverage-plugin
Hi,

We are currently trying to use the `check` goal with the scoverage-maven-plugin version: 1.4.1 and Scala version 2.12.13

When configuring scalacPluginVersions with value: `1.4.1` or `1.4.2` we get the following error:
`java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/report`

When using scalacPluginVersions: `1.4.3` or greater we get an error similar to the following:
`Could not find artifact org.scoverage:scalac-scoverage-plugin-2.12:jar:1.4.7 in <internal-repository>`); this is during the `pre-compile stage`

Based on this [sbt-scoverage issue](https://github.com/scoverage/sbt-scoverage/issues/319) we gather that the Scala 2.12.13 compiler not backwards compatible (resulting in the 1st error). I'm assuming this is why the scala-scoverage-plugin has begun to include Scala's patch version as part of it's artifactId.
Additionally, based on [SCoveragePreCompileMojo](https://github.com/scoverage/scoverage-maven-plugin/blob/master/src/main/java/org/scoverage/plugin/SCoveragePreCompileMojo.java#L250) we gather that the plugin ignores Scala's patch version when determining which version of the scalac-scoverage-plugin to use (resulting in the 2nd error).

If the above seems correct and reasonable, would you consider updating the maven plugin so that we are able to use a newer version of the scalac-scoverage-plugin - allowing us to use SCoverage with Scala 2.12.13?

Please let me know if the provided information is not sufficient.

Thanks,
Stewart

### PR DESCRIPTION
**Pull request by chetanmeh**
This PR implements the approach proposed in #94 . Post this it would be possible to use the maven plugin with Scala 2.12.13+

With this PR now plugin artifact lookup logic is done like below

1 First look for artifact having name like `scalac-scoverage-plugin_2.12.14` i.e. use the full version of Scala lib used in project
2 If that artifact is not found look for  `scalac-scoverage-plugin_2.12`

For this to work completely you still need to specify the `scalacPluginVersion` property. For example with Scala 2.12.14 we need version [scalac-scoverage-plugin - 1.4.8][1]

Fixes #94

[1]: https://github.com/scoverage/scalac-scoverage-plugin/releases/tag/v1.4.8

### CODE REVIEW

File: src/main/java/org/scoverage/plugin/SCoveragePreCompileMojo.java [hunk 1]
```diff
@@ -457,9 +457,20 @@ private Artifact getScalaScoveragePluginArtifact( String scalaMainVersion )
...
-            getResolvedArtifact( "org.scoverage", "scalac-scoverage-plugin_" + scalaMainVersion,
-                                 resolvedScalacPluginVersion );
+        try
+        {
+            // Look for plugin artifact matching the scala version (full form like 2.12.14)
+            // If not found then look for artifact based on major version like 2.12
+            result =
+                    getResolvedArtifact( "org.scoverage", "scalac-scoverage-plugin_" + resolvedScalaVersion,
+                            resolvedScalacPluginVersion );
+        } catch (ArtifactNotFoundException e)
```
Comment (stewartHutchins) [inline src/main/java/org/scoverage/plugin/SCoveragePreCompileMojo.java:467]: If an exception were thrown from both the above try-block the below catch-block caught, then the error message will only report not finding the `scalaMainVersion` (rather than both the `scalaMainVersion` and `resolvedScalaVersion`).

(I could be wrong though. Even if my comment is correct I don't whether a slightly inaccurate error message would be considered a good reason to block the pull request.)

**Review by stewartHutchins — COMMENTED** [review]
Baring my comment (which may not be a blocking issue) these change seem reasonable.

However, I'm not really familiar with the codebase or the community, so I'm not sure I'd be comfortable pressing approve (I assume there's some additional permissions I'd need to get before pressing approve anyway - however can't say for sure, as I'm not familiar with PRs on github either).

**Comment by marcoy** [comment]
At work, we just encountered this issue. We have to downgrade Scala in our projects which isn't ideal. It'd be great to have support for specifying the patch version.

**Comment by jozic** [comment]
@ckipp01 
is this something you can review/merge? 
pretty please )

**Comment by ckipp01** [comment]
> @ckipp01 is this something you can review/merge? pretty please )

Hey @jozic, for sure. Let me merge in the CI changes to github actions and I'll see if I can get this across the board. I'd like to get the CI updated and in place to actually ensure the tests are running correctly.

**Comment by sumeetgajjar** [comment]
Thanks @chetanmeh for creating the PR. We are facing a similar issue mentioned in #94. And this PR resolves the issue.

However, your branch looks old, could you please rebase your change on top of the latest `master`?
Your branch is still pointing to CircleCI which was replaced with GitHub actions in https://github.com/scoverage/scoverage-maven-plugin/commit/463b30902c3dae9dde435509848bb6f24f8ecf2a commit.

**Comment by gslowikowski** [comment]
Sorry for long delay. I will prepare new release soon.

**Comment by pgruetter** [comment]
Is there any workaround for this until the new release is out? Facing the same problem with scoverage-maven-plugin 1.4.1 throwing the error mentioned in post 1. If I'm correct, we would need to use a scalacPluginVersion 1.4.8. which we can't specify at the moment.

**Comment by gslowikowski** [comment]
Added an information in the logs suggested by @stewartHutchins in [the comment above](https://github.com/scoverage/scoverage-maven-plugin/pull/95#discussion_r690347364). To check it, build [this sample project](https://github.com/scoverage/scoverage-maven-samples/tree/scoverage-maven-samples-1.4.11/simple/sbt-compiler-plugin-scala-2.10). There will be:
```
[WARNING] Artifact "org.scoverage:scalac-scoverage-plugin_2.10.7:1.4.1" not found, falling back to "org.scoverage:scalac-scoverage-plugin_2.10:1.4.1"
```
message logged.

**Comment by gslowikowski** [comment]
Version `1.4.11` released.

**Comment by pgruetter** [comment]
@gslowikowski It's not available on maven central yet, is it still syncing?
